allowBuilds:
  esbuild: true
  simple-git-hooks: true

minimumReleaseAgeExclude:
  - '@triggerix/core'
  - '@triggerix/editor'
  - '@triggerix/registry'
  - '@types/node'

shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - nanoid
